import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'liste de naissance',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="fr">
      <body className={`antialiased`}>{children}</body>
    </html>
  )
}
